import io,sys
M=[('https://www.kisiizihospital.org.ug/wp-content/uploadedfiles/2013/10/UHC-PSQ-Learning-Lab-Doc_Final-Issued.pdf', 'files/who-uhc-patient-safety-2014.pdf'), ('https://www.kisiizihospital.org.ug/wp-content/uploadedfiles/2013/10/ICPIC-Kisiizi-paper-2013.pdf', 'files/icpic-kisiizi-2013.pdf'), ('https://www.kisiizihospital.org.ug/wp-content/uploadedfiles/2013/10/JOURNAL-OF-PUBLIC-HEALTH-IN-AFRICA2017-KISIIZI-STUDY-ATTITUDE-TO-FACILITIES-FOR-LABOR.pdf', 'files/jpha-labour-facilities-2017.pdf'), ('https://www.kisiizihospital.org.ug/wp-content/uploadedfiles/2019/06/volunteering_in_a_mental_health_service_in_uganda_challenges_and_rewards-1.pdf', 'files/bjpsych-volunteering-2019.pdf'), ('https://www.kisiizihospital.org.ug/wp-content/uploadedfiles/2019/06/Development-of-the-Kisiizi-hospital-health-insurance-scheme-Published-June-2018.pdf', 'files/khis-development-2018.pdf'), ('https://www.kisiizihospital.org.ug/wp-content/uploadedfiles/2019/06/KISIIZI-HOSPITAL-HEALTH-INSURANCE-SCHEME-article-08-2018.pdf', 'files/khis-scheme-2018.pdf'), ('https://www.kisiizihospital.org.ug/wp-content/uploadedfiles/2019/06/Effect-of-CBHI-on-Child-Health-and-Preventive-Health-thesis-KHIS-reced-9-2018.pdf', 'files/cbhi-child-health-thesis-2018.pdf'), ('https://www.kisiizihospital.org.ug/wp-content/uploadedfiles/2013/10/Hsern-Perth-Elective-report.pdf', 'files/elective-report-uwa-2014.pdf'), ('https://www.kisiizihospital.org.ug/wp-content/uploadedfiles/2013/10/Contact-mag-Dec-2013.pdf', 'files/wcc-contact-2013.pdf'), ('https://www.kisiizihospital.org.ug/wp-content/uploadedfiles/2013/10/APPS-News-autumn-13.pdf', 'files/who-apps-autumn-2013.pdf'), ('https://www.kisiizihospital.org.ug/wp-content/uploadedfiles/2013/10/Transformation-UPMB-newsletter-11-2015.pdf', 'files/upmb-transformation-2015.pdf'), ('https://www.kisiizihospital.org.ug/wp-content/uploadedfiles/2013/10/RCPCH-Newsletter-Spring-2013_web.pdf', 'files/rcpch-spring-2013.pdf')]
p=sys.argv[1]
h=io.open(p,encoding='utf-8').read()
n=0
for u,l in M:
    if u in h: h=h.replace(u,l); n+=1
io.open(p,'w',encoding='utf-8').write(h)
print('swapped %d links in %s'%(n,p))
